<a href="https://colab.research.google.com/github/KimballNJardine/MATH215/blob/main/Intro_to_Python_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lab 2 - Introduction to Python programming II**

Enter your code in the spaces provided. Do not change any of the variable names or function names that are already provided for you. In places where we specify the name of the return value, make sure that your code produces the a value with the correct name.

In [1]:
# Do not edit this cell.

LabID="Lab2"

try:
  from graderHelp import ISGRADEPLOT
except ImportError:
  ISGRADEPLOT = True

**Enter your name, section number, and BYU NetID**

In [2]:
# Enter your first and last names in between the quotation marks.

first_name="Kimball"

last_name="Jardine"

# Enter your Math 215 section number in between the quotation marks. 

section_number="001"  

# Enter your BYU NetID in between the quotation marks.  NOT YOUR BYU ID NUMBER!

BYUNetID="knj28"

**Problem 1**

In [3]:
first_elem=2   # Replace the value of 0 with the number described in Problem 1.

**Problem 2**

In [4]:
def sum_list(L):
  sum = 0
  for i in L:
    sum += i
  # Put your code here. 
  return sum # Put your return value here.

In [5]:
l = [0,1,2,3,4,5]
print(sum_list(l))

15


**Problem 3**

In [6]:
def list_relu(L):
  new_list=L.copy()  # Remember to create a copy of your list.  After this lab you'll need to remember to do it on your own.
  for i in range(len(new_list)):
    if(new_list[i] < 0):
      new_list[i] = 0
  # Put your code here. 
  return new_list# Put your return value here.

In [7]:
print(list_relu([-1, 0, 1, -5, 5.677]))

[0, 0, 1, 0, 5.677]


In [8]:
list1=[1,2,3]
list2=[2,-1,0]

print(list1+list2)

[1, 2, 3, 2, -1, 0]


**Problem 4**

In [9]:
import numpy as np  # Importing NumPy

In [10]:
array1=np.array(list1)
array2=np.array(list2)

print(array1+array2)
my_vect=np.array([1,2,-1])

print(3*my_vect)      # scalar multiplying my_vect by 3


a=np.array([1,2,3,1])     # Defining two vectors of the same size, a and b.
b=np.array([1,1,1,1])
np.dot(a,b)               # Taking the dot product of a and b. 


my_matrix=np.array([[1, 2, 3, 4],[-5, -6, -7, -8],[1, 5 , 2, 3]])
print(my_matrix)

[3 1 3]
[ 3  6 -3]
[[ 1  2  3  4]
 [-5 -6 -7 -8]
 [ 1  5  2  3]]


In [11]:
v=np.array([4,1,-5,3,-2,1,0,9])

print(v[3])         # Print out the entry at index 3 (i.e. the fourth entry)
                    # in the vector v.

print(v[2:6])       # Print out all entries in v between (and including)
                    # index 2 and index 5. Notice that the starting
                    # index 2 is included, but the stopping index 6 is not.

print(v[3:])        # Print out the entries starting at index 3 to the end
                    # of the vector.

print(v[:6])        # Print out the entries starting at the beginning of the
                    # vector up to the entry at index 5.

print(v[:])         # If we don't specify a start or stop index, we get back
                    # the whole array.

3
[-5  3 -2  1]
[ 3 -2  1  0  9]
[ 4  1 -5  3 -2  1]
[ 4  1 -5  3 -2  1  0  9]


In [12]:
my_matrix=np.array([[1, 2, 3, 4],[-5, -6, -7, -8],[1, 5, 2, 3]])

print(my_matrix[1,2])     # Print the element in the second row, third column
                          # of my matrix.

print(my_matrix[2,1:3])   # Print everything in the third row, from the second
                          # to the third column.

print(my_matrix[:,3])     # If we don't specify a start or stop index in the
                          # first spot, we get the entire fourth column.

print(my_matrix[2,:])     # If we don't specify a start or stop index in the
                          # second spot, we get the entire third row.

-7
[5 2]
[ 4 -8  3]
[1 5 2 3]


In [13]:
my_var= (np.e**5 - np.log(np.sqrt(5)))/np.e**np.cos(3)  # Replace the value of 0 with the required value from Problem 4.

**Problem 5**

In [14]:
v = np.array([1,3,-2,4,5])
u = np.array([1,1,-2,1,1])
w = np.array([1,0,1,0,1])

my_vect_var = (np.dot(v,u)/np.dot(u,u))*u + (np.dot(v,w)/np.dot(w,w))*w

**Problem 6**

In [15]:
def first_rpt(M):
  new_matrix=M.copy()  # Remember to create a copy of your matrix.  After this lab you'll need to remember to do it on your own.
  for i in range(len(M)):
    if(i > 0):
      for j in range(len(M[0])):
        new_matrix[i,j] = M[0,j]

  return new_matrix

In [16]:
my_matrix=np.array([[1, 2, 3, 4],[-5, -6, -7, -8],[1, 5, 2, 3]])
print(my_matrix)
print(first_rpt(my_matrix))

[[ 1  2  3  4]
 [-5 -6 -7 -8]
 [ 1  5  2  3]]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [17]:
a=[i*j for i in range(1,4) for j in range(2,5)]
print(a)

[2, 3, 4, 4, 6, 8, 6, 9, 12]


**Problem 7**

In [18]:
def matrix_sum(M):
  sum = 0
  rows = len(M)
  cols = len(M[0,:])
  for i in range(rows):
    for j in range(cols):
      sum += M[i,j]
  return sum

In [19]:
mat=np.array([[1,-1,2,-3,1,1],[-2,-2,0,1,1,-5],[1,1,1,1,-2,-1]])
print(matrix_sum(mat))

-5


**Problem 8**

In [20]:
long_list=[0.5**i for i in range(1,101)]  # Replace the value of 0 with the required list from Problem 8.

In [21]:
print(long_list[-1])
print(0.5**100)

7.888609052210118e-31
7.888609052210118e-31


**Problem 9**

In [22]:
very_long_list=[f**i for i in range(1,100) for f in [1, 2, 3]]

In [23]:
print(very_long_list[0:10])

[1, 2, 3, 1, 4, 9, 1, 8, 27, 1]


**STOP!  BEFORE YOU SUBMIT THIS LAB:**  Go to the "Runtime" menu at the top of this page, and select "Restart and run all".  If any of the cells produce error messages, you will either need to fix the error(s) or delete the code that is causing the error(s).  Then use "Restart and run all" again to see if there are any new errors.  Repeat this until no new error messages show up.  

**You are not ready to submit until you are able to select "Restart and run all" without any new error messages showing up.  Your code will not be able to be graded if there are any error messages.**

To submit your lab for grading you must first download it to your compute as .py file. In the "File" menu select "Download .py". The resulting file can then be uploaded to http://www.math.byu.edu:30000 for grading.